### ISSUE TITLE
borked matrix1d?

### ISSUE THREAD

**Issue by notnullnotvoid** [h3rb/ZeroTypes#1]
was just poking around to see what kind of stuff was in this project, and noticed this:

https://github.com/h3rb/ZeroTypes/blob/master/ZeroTypes/macros.h#L93

not sure what this is supposed to do, but it looks like it will always index outside the valid bounds of the vector. or are my eyes broken?

**Comment by h3rb** [comment]
Whoa, didn't see this FOREVER.  I don't really use matrix1d so that may explain why it's got an issue with it.  Will try to fix.

**Comment by h3rb** [comment]
Fixed
